version: "3"
# https://github.com/DataDog/docker-compose-example
services:
  web:
    build: .
    ports:
    - "8080:8080"
    environment:
    - DATADOG_HOST=datadog # used by the web app to initialize the Datadog library
    depends_on: [datadog]

  datadog:
    build: datadog
    # NOTE: This will make sure to wait for web service
    # https://docs.docker.com/compose/compose-file/#links
    # links:
    # - web # ensures that the web app can send metrics
    environment:
    # https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml
    - DD_API_KEY
    - DD_SITE=datadoghq.eu
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    - DD_DOGSTATSD_ORIGIN_DETECTION=true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /proc/:/host/proc/:ro
    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
