version: "3"
# https://github.com/DataDog/docker-compose-example
services:
  web:
    build: web
    ports:
     - "8080:8080"
    environment:
     - DATADOG_HOST=datadog # used by the web app to initialize the Datadog library
  # datadog:
  #   build: datadog
  #   links:
  #    - web # ensures that the web app can send metrics
  #   environment:
  #   - DD_SITE=datadoghq.eu
  #   - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
  #   volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - /proc/:/host/proc/:ro
  #    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
